server:
  port: 8088

spring:
  application:
    name: share-spring-cloud
    
zuul:
  routes:
    name1:
      path: /test/*
      url: http://localhost:8080/
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/